# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'M', max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(default=b'0000000', max_length=8)),
            ],
        ),
    ]
